[package]
name = "cl-bot"
version = "0.1.0"
authors = ["Jerry Tegno <jerrytegno@gmail.com>"]

[dependencies]
clap = "2.31"
nom = "4.0"
rayon = "1.0"
reqwest = "0.8"
rusqlite = { version = "0.13", features = ["bundled"] }
select = "0.4"
serde = "1.0"
serde_derive = "1.0"
toml = "0.4"
