[package]
name = "cl-bot"
version = "0.1.0"
authors = ["Jerry Tegno <jerrytegno@gmail.com>"]

[dependencies]
clap = "2.31.2"
combine = "3.3.2"
nom = "4.0.0"
rayon = "1.0.1"
reqwest = "0.8.6"
rusqlite = "0.13.0"
select = "0.4.2"
serde = "1.0.66"
serde_derive = "1.0.66"
toml = "0.4.6"
