[package]
name = "cl-bot"
version = "0.1.0"
authors = ["Jerry Tegno <jerrytegno@gmail.com>"]

[dependencies]
env_logger = "0.5.13"
failure = "0.1.3"
log = "0.4.6"
nom = "4.1.1"
rayon = "1.0.3"
reqwest = "0.9.4"
rusqlite = { version = "0.15.0", features = ["bundled"] }
select = "0.4.2"
serde = "1.0.80"
serde_derive = "1.0.80"
structopt = "0.2.13"
toml = "0.4.8"
