[telegram]
token = 'bot_key_here'
chat_id = 12345678

[[searches]]
url = 'https://sfbay.craigslist.org/search/sfc/sga?query=snowboard'

[[searches]]
url = 'https://sfbay.craigslist.org/search/sfc/sss?query=snowboard+boots'
